# Continuous Integration workflow for bufferin.nvim
# Runs tests, linting, and formatting checks on every push and pull request

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Run test suite on multiple Neovim versions
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        neovim_version:
          - stable    # Latest stable release
          - nightly   # Development version

    steps:
    # Checkout the repository
    - uses: actions/checkout@v3

    # Install Neovim
    - name: Install Neovim
      uses: rhysd/action-setup-vim@v1
      with:
        neovim: true
        version: ${{ matrix.neovim_version }}

    # Install test framework
    - name: Install Plenary
      run: |
        git clone https://github.com/nvim-lua/plenary.nvim.git ~/.local/share/nvim/site/pack/vendor/start/plenary.nvim

    # Run test suite
    - name: Run tests
      run: |
        nvim --headless -u tests/minimal_init.lua -c "PlenaryBustedDirectory tests/ { minimal_init = './tests/minimal_init.lua', sequential = true }"

  # Run luacheck linter
  lint:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - uses: actions/checkout@v3

    # Install luacheck
    - name: Install luacheck
      run: |
        sudo apt-get update
        sudo apt-get install -y luarocks
        sudo luarocks install luacheck

    # Run linter
    - name: Run luacheck
      run: luacheck lua/

  # Check code formatting
  format:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - uses: actions/checkout@v3

    # Install and run stylua
    - name: Install stylua
      uses: JohnnyMorganz/stylua-action@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        version: latest
        args: --check lua/